### ISSUE TITLE
globalThis.Semaphore warning

### ISSUE THREAD

**Issue by grz0** [moo-man/WarhammerLibrary-FVTT#4]
The following warning is logged in the dev console:
> Error: You are accessing globalThis.Semaphore which must now be accessed via foundry.utils.Semaphore
> Deprecated since Version 12
> Backwards-compatible support will be removed in Version 14
>     at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
>     at get (foundry-esm.js:66671:25)
>     at <static_initializer> (warhammer.js:3300:24)
>     at warhammer.js:3297:21

![image](https://github.com/user-attachments/assets/d2d0e708-0548-4608-a2fb-6aedd4846118)

**Comment by moo-man** [comment]
Closed in #3
